### ISSUE TITLE
Allow proxies for downloading

### ISSUE THREAD

**Issue by pedrofracassi** [Geomitron/Bridge#22]
As Google hasn't provided a solution for the problem reported in #20, wouldn't proxies be a viable solution for the ratelimits? Maybe allow the user to provide proxies through a `proxies.txt` file somewhere, or in the program's settings?

**Comment by Geomitron** [comment]
I'm implementing my own version of chart downloading that doesn't involve the user logging in to Google, and downloads should just be fast and work. The Google login has been removed from the latest version.
