### ISSUE TITLE
Flatpak Support

### ISSUE THREAD

**Issue by LegitGreenBoi** [Geomitron/Bridge#41]
Really like this program and I'd love to see a Flatpak version hosted on Flathub be made if possible.

Due to some [bugs](https://github.com/TheAssassin/AppImageLauncher/issues/518) with popular software like AppImage Launcher, appimages can be unreliable on some Linux Distros. Flatpaks tend to be much more consistent across distros in my experience.

**Comment by Formedras** [comment]
The AppImage is working fine for me (after a false start which my computer just does sometimes), but I support this just on the idea that one of the promises of Linux is choice. Until you hit choice paralysis, the more the better. DEB and RPM packages would be nice too.

**Comment by binarygeek119** [comment]
i 1+ this as i cant use the appimage as im on zorin os and it uses wayland which doesnt play nice with appimage

**Comment by Geomitron** [comment]
I've also found that the AppImage version takes an unreasonable amount of time to start.

The next version will include a Flatpak release. Nothing on Flathub for now; maybe some time in the future when it becomes easier to set up.

**Comment by LegitGreenBoi** [comment]
> I've also found that the AppImage version takes an unreasonable amount of time to start.
> 
> The next version will include a Flatpak release. Nothing on Flathub for now; maybe some time in the future when it becomes easier to set up.

A Flathub listing would be great, but in the meantime, the Flatpak build is much appreciated!
