### ISSUE TITLE
arm64 release "is damaged and can't be opened"

### ISSUE THREAD

**Issue by MikkyX** [Geomitron/Bridge#54]
Downloaded the arm64 .dmg for v2.1.0 (M1 Mac Mini) and when opening it after dragging it to Applications I get this error:

<img width="270" alt="image" src="https://github.com/Geomitron/Bridge/assets/7023132/a474d28b-25a3-4105-a0d6-90477edfa85f">

Same message if I try to install it from the Zip download.

**Comment by jensyfrenzy** [comment]
Also running into this issue on M1 Pro MacBook

**Comment by Geomitron** [comment]
Mac builds have been updated. Let me know if they don't work for you

**Comment by MikkyX** [comment]
Still got the error on arm64 2.1.0 but I'm able to use the x64 build, although there was a Promise Rejection error on opening it - if I'm able to capture that again I'll let you know.

**Comment by haroldthegray** [comment]
Experiencing the same problem with 3.0.0 arm64.
The non-arm64 3.0.0 version seems to work fine as an alternate.
