### ISSUE TITLE
V2.1.0 Release missing Mac x64 option

### ISSUE THREAD

**Issue by jgbowser** [Geomitron/Bridge#55]
It seems that `electron-builder` defaults to the current system type when building an app if multiple architectures are not specified. I believe the configuration for mac needs to include targets for both x64 and arm64 architectures.

**Comment by Geomitron** [comment]
Mac builds have been updated. Let me know if they don't work for you

**Comment by willnewcombe** [comment]
I think the mac builds are being omitted again?
