### ISSUE TITLE
Chart Library Directory SMB Share (permissions issue?)

### ISSUE THREAD

**Issue by arette** [Geomitron/Bridge#58]
I appear to be having permissions issues with the chart library directory set to smb share from my NAS (where I store my clone hero songs).  Sometimes it produces file already exists error and sometimes it produces no such file or directory error, but it always manages to create a 0 KB file before producing an error. Again, my hunch is that this is permissions issue, but not sure how to confirm that and resolve it. Thank you for this tool! :)

![Screenshot 2024-02-18 103130](https://github.com/Geomitron/Bridge/assets/12751515/14ead1da-3425-455a-90e8-9feef0a31153)
![Screenshot 2024-02-18 103431](https://github.com/Geomitron/Bridge/assets/12751515/6408edad-938e-4a92-8275-e678283a082f)
![Screenshot 2024-02-18 102925](https://github.com/Geomitron/Bridge/assets/12751515/4ccc378b-6342-4061-a267-1491894af8bc)

**Comment by Geomitron** [comment]
As far as I can tell, this is a limitation of NodeJS; it can't move files to network directories.
https://stackoverflow.com/questions/67570614/using-g-google-drive-for-desktop-for-node-js-projects-npm-install-errors

I'm not sure how to fix this, and since this is not a common issue, it's low priority for me. If you or anyone else can find a solution, I will try implementing it.

**Comment by imaustinlittle** [comment]
I am having a similar issue saving songs to my Google Drive that is mounted as a "physical drive".

**Comment by Spinny319** [comment]
Wonder if it has to do with it adding extra back slashes in the file path? Could just be a GUI bug with the error too. Great work on the tool so far 👍
![image](https://github.com/Geomitron/Bridge/assets/130417833/fc426220-fb1a-4150-bf24-aeecab2c2b5e)

**Comment by Spinny319** [comment]
@arette Mapping your SMB share as a network drive (giving it a drive letter on your local system) seems to be a pretty easy workaround. I haven't had any "file moving" errors since.

**Comment by Geomitron** [comment]
since @Spinny319 's solution appears to work, I'll close this issue. If there are still problems using network folders with Bridge, I can attempt to fix this if I get specific examples of what doesn't work.
