### ISSUE TITLE
Allow changing the download path with string expansions/format strings

### ISSUE THREAD

**Issue by devcutler** [Geomitron/Bridge#68]
In many download manager programs like this there is the option to format strings with a custom format, for better organization. This often has options such as the file name, the current date or time, or the category/genre of the item. For this in particular, I think all of the options you can search by would be useful.

For example, if I wanted to sort by artist, then album, then song name, I'd use something like the following:
```
basepath/%artist%/%album%/%name%/
basepath/{artist}/{album}/{name}/
basepath/{artist}/{album}/{name}.sng
```

In Clone Hero, you can both show and sort by subfolder, named Playlist. If you're organizing a lot of songs, this would be helpful to sort through them faster, and to prevent having to manually sort the folders after downloading, the whole point of Bridge to begin with.

The last part of the provided path (`path.basename(path)` in this case) can serve as either the filename without extension (for SNG files) or the final folder name (for song folders).

PR incoming soon, unless you have a method of implementing this that you particularly want.

Reference as example: https://wiki.videolan.org/Documentation:Format_String

**Comment by Geomitron** [comment]
I like that idea; I'll merge a PR for it if you make it. The UI for this should be a text input on the settings tab, with it initially set to the default format string. There should be a help pop-up like the download format has to explain the field and the valid values it can have.

**Comment by Geomitron** [comment]
This feature will be included in the next release
